#!/usr/bin/env bash
# Generates web/firebase-config.js (gitignored) before flutter build web.
# Reads WPGG_FIREBASE_API_KEY from the environment (e.g. Vercel build env).

set -euo pipefail

API_KEY="${WPGG_FIREBASE_API_KEY:-}"
AUTH_DOMAIN="${FIREBASE_AUTH_DOMAIN:-wpgg-7e831.firebaseapp.com}"
PROJECT_ID="${FIREBASE_PROJECT_ID:-wpgg-7e831}"
STORAGE_BUCKET="${FIREBASE_STORAGE_BUCKET:-wpgg-7e831.firebasestorage.app}"
MESSAGING_SENDER_ID="${FIREBASE_MESSAGING_SENDER_ID:-966474300066}"
APP_ID="${FIREBASE_APP_ID:-1:966474300066:web:d50c60fc81bac09d80f5fb}"
MEASUREMENT_ID="${FIREBASE_MEASUREMENT_ID:-G-7FE09H8SDH}"

if [[ -z "$API_KEY" ]]; then
  echo "WPGG_FIREBASE_API_KEY is required." >&2
  exit 1
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/web/firebase-config.js"

cat >"$OUT" <<EOF
// Generated by scripts/prepare-firebase-web.sh — do not commit.
self.firebaseConfig = {
  apiKey: '$API_KEY',
  authDomain: '$AUTH_DOMAIN',
  projectId: '$PROJECT_ID',
  storageBucket: '$STORAGE_BUCKET',
  messagingSenderId: '$MESSAGING_SENDER_ID',
  appId: '$APP_ID',
  measurementId: '$MEASUREMENT_ID',
};
EOF

echo "Wrote $OUT"
