# Generates web/firebase-config.js (gitignored) before flutter build web.
# Pass keys via env vars or --dart-define values exported here.

param(
    [string]$ApiKey = $env:WPGG_FIREBASE_API_KEY,
    [string]$AuthDomain = $env:FIREBASE_AUTH_DOMAIN,
    [string]$ProjectId = $env:FIREBASE_PROJECT_ID,
    [string]$StorageBucket = $env:FIREBASE_STORAGE_BUCKET,
    [string]$MessagingSenderId = $env:FIREBASE_MESSAGING_SENDER_ID,
    [string]$AppId = $env:FIREBASE_APP_ID,
    [string]$MeasurementId = $env:FIREBASE_MEASUREMENT_ID
)

$defaults = @{
    AuthDomain        = 'wpgg-7e831.firebaseapp.com'
    ProjectId        = 'wpgg-7e831'
    StorageBucket    = 'wpgg-7e831.firebasestorage.app'
    MessagingSenderId = '966474300066'
    AppId            = '1:966474300066:web:d50c60fc81bac09d80f5fb'
    MeasurementId    = 'G-7FE09H8SDH'
}

if (-not $AuthDomain) { $AuthDomain = $defaults.AuthDomain }
if (-not $ProjectId) { $ProjectId = $defaults.ProjectId }
if (-not $StorageBucket) { $StorageBucket = $defaults.StorageBucket }
if (-not $MessagingSenderId) { $MessagingSenderId = $defaults.MessagingSenderId }
if (-not $AppId) { $AppId = $defaults.AppId }
if (-not $MeasurementId) { $MeasurementId = $defaults.MeasurementId }

if (-not $ApiKey) {
    Write-Error 'WPGG_FIREBASE_API_KEY is required. Example: $env:WPGG_FIREBASE_API_KEY=AIza... ./scripts/prepare-firebase-web.ps1'
    exit 1
}

$root = Split-Path -Parent $PSScriptRoot
$outPath = Join-Path $root 'web/firebase-config.js'

$content = @"
// Generated by scripts/prepare-firebase-web.ps1 — do not commit.
self.firebaseConfig = {
  apiKey: '$ApiKey',
  authDomain: '$AuthDomain',
  projectId: '$ProjectId',
  storageBucket: '$StorageBucket',
  messagingSenderId: '$MessagingSenderId',
  appId: '$AppId',
  measurementId: '$MeasurementId',
};
"@

Set-Content -Path $outPath -Value $content -Encoding UTF8
Write-Host "Wrote $outPath"
